### ISSUE TITLE
What are *.ref entries created in consul

### ISSUE THREAD

**Issue by bitsofinfo** [breser/git2consul#114]
Hi, - we are replicating certain tags i.e. 1.0.0.1, 1.0.0.2, but in consul we end up w/ a structure like

1.0.0.1
1.0.0.1.ref
1.0.0.2
1.0.0.2.ref

Please explain, and is there a way to get rid of the refs.

**Comment by davidnewman** [comment]
I am assuming you have "support_tags" enabled in your git2consul config?

The *.ref files contain the commit hash (ref) of the commit the tag points to. This is used by git2consul to determine if the tag has changed, and thus whether the keys need to be updated.
