### ISSUE TITLE
Support git-crypt

### ISSUE THREAD

**Issue by Yekut** [breser/git2consul#134]
This idea is either very useful or just purely feature creep - currently there's no support for git-crypt, and git2consul will happily push encrypted values to Consul. There's a very hacky workaround - first checkout the repo and manually unlock, then point git2consul to the checked out repo as its local_store parameter. OTOH, this can be very brittle, e.g., when git2consul decides to delete and re-clone it'll probably suddenly push the encrypted value. Is this a fine workaround, or should people just use Vault instead of git2consul + git-crypt for managing secret values?

**Comment by calvn** [comment]
This is similar to #131. I reccommended git2consul + gosecret + fsconsul for transporting secrets across the network, but there are certainly other solutions such as Vault like you mentioned.
