### ISSUE TITLE
Local protocol

### ISSUE THREAD

**Issue by CodingTink** [breser/git2consul#158]
Hi,
I'm habving trouble setting up git2consul with a local repo. No errors, but the files aren't mirrored to Consul. Works fine with ssh protocol though. Am I missing something here?
{
    "version": "1.0",
    "repos" : [{
        "name" : "myrepo",
        "expand_keys_diff": true,
        "url" : "/data/git/myrepo",
        "branches" : ["master"],
        "hooks" : [{
            "type" : "polling",
            "interval" : 1
        }]
    }]
}

{"name":"git2consul","hostname":"431a91b7e519","pid":15849,"level":30,"msg":"Adding /etc/git2consul.d/config.json to KV git2consul/config as: \n{\n    \"version\": \"1.0\",\n    \"repos\" : [{\n\t\"name\" : \"myrepo\",\n        \"expand_keys_diff\": true,\n        \"url\" : \"/data/git/myrepo\",\n        \"branches\" : [\"master\"],\n        \"hooks\" : [{\n            \"type\" : \"polling\",\n            \"interval\" : 1\n        }]\n    }]\n}\n","time":"2017-09-08T07:49:23.339Z","v":0}
{"name":"git2consul","hostname":"431a91b7e519","pid":15849,"level":30,"msg":"git2consul is running","time":"2017-09-08T07:49:23.470Z","v":0}
{"name":"git2consul","hostname":"431a91b7e519","pid":15849,"level":30,"msg":"Initting repo myrepo","time":"2017-09-08T07:49:23.472Z","v":0}
{"name":"git2consul","hostname":"431a91b7e519","pid":15849,"level":30,"msg":"Initting branch /tmp/myrepo /tmp/myrepo/master","time":"2017-09-08T07:49:23.472Z","v":0}
{"name":"git2consul","hostname":"431a91b7e519","pid":15849,"level":30,"msg":"Initialized branch master from myrepo","time":"2017-09-08T07:49:23.584Z","v":0}
{"name":"git2consul","hostname":"431a91b7e519","pid":15849,"level":30,"msg":"Loaded repo myrepo","time":"2017-09-08T07:49:23.584Z","v":0}

**Comment by marcindulak** [comment]
Works for me https://github.com/breser/git2consul/issues/175
